name: medical-insurance
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pandas=2.1.4
  - numpy=1.26.2
  - matplotlib=3.8.2
  - seaborn=0.13.0
  - scikit-learn=1.3.2
  - scipy=1.11.4
  - pip
  - pip:
    - jupyter==1.0.0
    - notebook==7.0.6
    - plotly==5.18.0
    - psutil==5.9.6
